
mybatis:
  mapper-locations: classpath:com/geekgame/demo/dao/*.xml

server:
  port: 8082


worker:
  id: 1

logging:
  level:
    root: info

spring:
  datasource:
    password: xxxxxxxx
    url:  xxxxxxxx
    username: root
    type:  xxxxxxxx
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false

  redis:
    host: xxx.xxx.xxx.xxx
    password:  xxxxxxxx
    port: 6379





